apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-end
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: front-end
    spec:
      containers:
      - env:
        - name: CHOKIDAR_USEPOLLING
          valueFrom:
            configMapKeyRef:
              key: CHOKIDAR_USEPOLLING
              name: env-front-end-env
        image: front-end
        imagePullPolicy: ""
        name: onetool-frontend
        ports:
        - containerPort: 3000
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
