apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "8888"
    port: 8888
    targetPort: 8888
  - name: "443"
    port: 443
    targetPort: 443
    nodePort: 30000
  selector:
    io.kompose.service: php
  type: LoadBalancer
status:
  loadBalancer: {}
