version: '3.3'

services:

  # Redis Master Node for Caching & Streaming
  redis-master:
    container_name: onetool_redis_master
    build:
      context: ./Redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
    volumes:
      - '/redis'
      

  # Grafana Node for Metrics Display
  grafana:
    container_name: onetool_grafana
    image: "grafana/grafana:5.4.1"
    ports:
      - "4000:3000"
    user: "472"
    volumes:
      - "grafana-data:/var/lib/grafana"


  # MySQL DB as the Main DB engine
  mysql:
    container_name: onetool_mysql_db
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db-data:/var/lib/mysql


  # PHP Backend App
  php:
    container_name: onetool_php
    build:
      context: ./
      dockerfile: ./back-end/.docker/php/Dockerfile
    image: php:7.4-fpm
    volumes:
      - ./back-end/app:/var/www/html
    env_file:
      - env/php/php.redis.env
      - env/php/php.mysql.env
      - env/php/php.stream.env
      - env/php/php.frontend.env
    ports:
      - "8000:8000"
      - "9000:9000"
      - "8888:8888"
      - "443:443"
    depends_on:
      - grafana
      - redis-master
      - mysql


  # Front end Node
  front-end:
    container_name: onetool-frontend
    image: node:13.12.0-alpine
    build:
      context: ./front-end/app
      dockerfile: 'Dockerfile'
    volumes:
      - './front-end:/app'
      - './front-end/app/node_modules:/app/node_modules'
    ports:
      - 3000:3000
    env_file:
      - env/front-end.env


volumes:
  grafana-data:
  redis-master:
  db-data:
