version: '3.3'

services:

  # Redis Master Node for Caching & Streaming
  redis-master:
    container_name: onetool_redis_master
    build:
      context: ./Redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
    tty: true

  
  # Prometheus for Metrics
  prom:
    container_name: onetool_prom
    ports:
      - "9090:9090"
    build:
      context: ./
      dockerfile: ./back-end/.docker/prometheus/Dockerfile
    tty: true


  # Grafana Node for Metrics Visualization
  grafana:
    container_name: onetool_grafana
    image: "grafana/grafana:5.4.1"
    ports:
      - "4000:3000"
    user: "472"
    tty: true


  # MySQL DB as the Main DB engine
  mysql:
    container_name: onetool_mysql_db
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    tty: true


  # PHP Backend App
  php:
    container_name: onetool_php
    build:
      context: ./
      dockerfile: ./back-end/.docker/php/Dockerfile
    env_file:
      - env/php/php.redis.env
      - env/php/php.mysql.env
      - env/php/php.stream.env
      - env/php/php.frontend.env
    ports:
      - "8000:8000"
      - "9000:9000"
      - "8888:8888"
      - "443:443"
    depends_on:
      - grafana
      - redis-master
      - mysql
    tty: true


  # Front end Node
  front-end:
    container_name: onetool-frontend
    build:
      context: ./front-end/app
      dockerfile: 'Dockerfile'
    ports:
      - 3000:3000
    env_file:
      - env/front-end.env
    tty: true

