version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-alpine
    steps:
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run:
          name: Install App Infrastructure
          command: make install
      - run:
          name: Install App
          command: make appinstall
      - run:
          name: Start App
          command: make start
      - run:
          name: Test App
          command: make test
      - run:
          name: Generate Test Logs
          command: docker exec -it onetool_php ./vendor/bin/phpunit --coverage-clover coverage.xml
      
