version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:

      - run:
          name: Install Dependencies
          command: TZ=Europe/Minsk && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && apt-get update && apt-get install -y git build-essential
      - run:
          name: Install Docker
          command: apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
      - run:
          name: Cloning Project
          command: cd ~/project && git clone https://github.com/manonworld/manon.git .
      - run:
          name: Install App Infrastructure
          command: cd ~/project && make install
      - run:
          name: Install App
          command: cd ~/project && make appinstall
      - run:
          name: Start App
          command: cd ~/project && make start
      - run:
          name: Test App
          command: cd ~/project && make test
      - run:
          name: Generate Test Logs
          command: docker exec -it onetool_php ./vendor/bin/phpunit --coverage-clover coverage.xml
      
