# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

FROM bitnami/redis

COPY redis.conf /usr/share/defaults/etc/redis.conf

CMD [ "redis-server", "/usr/share/defaults/etc/redis.conf" ]